require('plugins/packer')
require('plugins/nord')
require('plugins/tree')
require('plugins/navic')
require('plugins/barbar')
--require('plugins/barbecue')
require('plugins/cursorline')
require('plugins/dashboard')
require('plugins/lspconfig')
require('plugins/lualine')
require('plugins/autoclose')

